// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {dl} from '../models';

export function CancelAnimeDownloads(arg1:string):Promise<void>;

export function ClearProgress():Promise<void>;

export function FetchCredentialsFromChrome():Promise<Record<string, string>>;

export function GetConfig():Promise<config.Config>;

export function GetEpisodes(arg1:string,arg2:string):Promise<Array<main.EpisodeInfo>>;

export function GetPosterBase64(arg1:string):Promise<string>;

export function GetProgress():Promise<Array<dl.JobProgress>>;

export function IsOnline():Promise<boolean>;

export function RetryFailed(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;

export function SearchAnime(arg1:string):Promise<Array<main.AnimeResult>>;

export function SelectDirectory():Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;
