// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tracker} from '../models';
import {api} from '../models';
import {config} from '../models';
import {main} from '../models';
import {dl} from '../models';

export function BatchTrackAnime(arg1:Array<tracker.TrackedAnime>):Promise<number>;

export function CancelAnimeDownloads(arg1:string):Promise<void>;

export function CheckTrackedUpdatesNow():Promise<void>;

export function ClearProgress():Promise<void>;

export function FetchCredentialsFromBrowser():Promise<Record<string, string>>;

export function GetAnimeMetadata(arg1:string):Promise<api.MetadataResult>;

export function GetConfig():Promise<config.Config>;

export function GetEpisodes(arg1:string,arg2:string,arg3:string):Promise<Array<main.EpisodeInfo>>;

export function GetPosterBase64(arg1:string):Promise<string>;

export function GetProgress():Promise<Array<dl.JobProgress>>;

export function GetServerStatus():Promise<boolean|number>;

export function GetTrackedAnime():Promise<Array<tracker.TrackedAnime>>;

export function IsAnimeTracked(arg1:string):Promise<boolean>;

export function IsOnline():Promise<boolean>;

export function OpenDownloadFolder():Promise<void>;

export function RetryFailed(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number,arg11:boolean,arg12:boolean,arg13:boolean,arg14:boolean,arg15:boolean,arg16:number,arg17:string):Promise<void>;

export function SearchAnime(arg1:string,arg2:string):Promise<Array<main.AnimeResult>>;

export function SelectBrowserFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<void>;

export function StartStreamingServer():Promise<void>;

export function StopStreamingServer():Promise<void>;

export function ToggleTrackAnime(arg1:string,arg2:string,arg3:string):Promise<boolean>;
