// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAnimeDownloads(arg1) {
  return window['go']['main']['App']['CancelAnimeDownloads'](arg1);
}

export function ClearProgress() {
  return window['go']['main']['App']['ClearProgress']();
}

export function FetchCredentialsFromChrome() {
  return window['go']['main']['App']['FetchCredentialsFromChrome']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEpisodes(arg1, arg2) {
  return window['go']['main']['App']['GetEpisodes'](arg1, arg2);
}

export function GetPosterBase64(arg1) {
  return window['go']['main']['App']['GetPosterBase64'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function IsOnline() {
  return window['go']['main']['App']['IsOnline']();
}

export function RetryFailed(arg1) {
  return window['go']['main']['App']['RetryFailed'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SearchAnime(arg1) {
  return window['go']['main']['App']['SearchAnime'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3);
}
