// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchTrackAnime(arg1) {
  return window['go']['main']['App']['BatchTrackAnime'](arg1);
}

export function CancelAnimeDownloads(arg1) {
  return window['go']['main']['App']['CancelAnimeDownloads'](arg1);
}

export function CheckTrackedUpdatesNow() {
  return window['go']['main']['App']['CheckTrackedUpdatesNow']();
}

export function ClearProgress() {
  return window['go']['main']['App']['ClearProgress']();
}

export function FetchCredentialsFromBrowser() {
  return window['go']['main']['App']['FetchCredentialsFromBrowser']();
}

export function GetAnimeMetadata(arg1) {
  return window['go']['main']['App']['GetAnimeMetadata'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEpisodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEpisodes'](arg1, arg2, arg3);
}

export function GetPosterBase64(arg1) {
  return window['go']['main']['App']['GetPosterBase64'](arg1);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetTrackedAnime() {
  return window['go']['main']['App']['GetTrackedAnime']();
}

export function IsAnimeTracked(arg1) {
  return window['go']['main']['App']['IsAnimeTracked'](arg1);
}

export function IsOnline() {
  return window['go']['main']['App']['IsOnline']();
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function RetryFailed(arg1) {
  return window['go']['main']['App']['RetryFailed'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
}

export function SearchAnime(arg1, arg2) {
  return window['go']['main']['App']['SearchAnime'](arg1, arg2);
}

export function SelectBrowserFile() {
  return window['go']['main']['App']['SelectBrowserFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4);
}

export function StartStreamingServer() {
  return window['go']['main']['App']['StartStreamingServer']();
}

export function StopStreamingServer() {
  return window['go']['main']['App']['StopStreamingServer']();
}

export function ToggleTrackAnime(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleTrackAnime'](arg1, arg2, arg3);
}
